colors:
  # Default colors
  primary:
    background: "0xfafafa"
    foreground: "0x383a42"

  cursor:
    text: "0xf0f0f0"
    cursor: "0x4078f2"

  selection:
    text: "0xfafafa"
    background: "0xa0bcf8"

  # Normal colors
  normal:
    black: "0x1b2229"
    red: "0xe45649"
    green: "0x50a14f"
    yellow: "0xf9a824"
    blue: "0x4078f2"
    magenta: "0xa626a4"
    cyan: "0x0184bc"
    white: "0xe7e7e7"

  # Bright colors
  bright:
    black: "0x1b2229"
    red: "0xe45649"
    green: "0x50a14f"
    yellow: "0xf9a824"
    blue: "0x4078f2"
    magenta: "0xa626a4"
    cyan: "0x0184bc"
    white: "0xe7e7e7"

  # Dim colors
  #
  # If the dim colors are not set, they will be calculated automatically based
  # on the `normal` colors.
  # dim:
  #   black: "0x000000"
  #   red: "0x8c3336"
  #   green: "0x7a8530"
  #   yellow: "0x97822e"
  #   blue: "0x506d8f"
  #   magenta: "0x80638e"
  #   cyan: "0x497e7a"
  #   white: "0x9a9a9a"
# Background opacity
#
# Window opacity as a floating point number from `0.0` to `1.0`.
# The value `0.0` is completely transparent and `1.0` is opaque.
#background_opacity: 1.0
