# luna_pinyin.custom.yaml

__patch:
  # Rx: emoji:customize:schema=luna_pinyin_simp
  - patch/+:
      __include: emoji_suggestion:/patch

patch:
  "translator/dictionary": luna_pinyin.extended
  punctuator/symbols:
    # 个人常用信息
    "/zt": [ztlevi.work@gmail.com, ztlevi1993@gmail.com, zhot@amazon.com, ztlevi]
    # 快速输入勾和叉
    "/ck": [✓, ✗, ☒]
  switches: # 注意缩进
    - name: ascii_mode
      reset: 0 # reset 0 的作用是当从其他输入法切换到本输入法重设为指定状态
      states: [中文, 西文] # 选择输入方案后通常需要立即输入中文，故重设 ascii_mode = 0
    - name: full_shape
      states: [半角, 全角] # 而全／半角则可沿用之前方案的用法。
    - name: simplification
      reset: 1 # 增加这一行：默认启用「繁→簡」转换。 范德薩范德薩
      states: [漢字, 汉字]
  "speller/algebra":
    - erase/^xx$/ # 第一行保留

    # 模糊音定義
    # - derive/^([zcs])h/$1/ # zh, ch, sh => z, c, s
    # - derive/^([zcs])([^h])/$1h$2/ # z, c, s => zh, ch, sh

    # - derive/^n/l/ # n => l
    # - derive/^l/n/ # l => n

    # 這兩組一般是單向的
    #- derive/^r/l/                     # r => l

    # - derive/^ren/yin/ # ren => yin, reng => ying
    #- derive/^r/y/                     # r => y

    # 韻母部份
    # - derive/^([bpmf])eng$/$1ong/ # meng = mong, ...
    - derive/([ei])n$/$1ng/ # en => eng, in => ing
    - derive/([ei])ng$/$1n/ # eng => en, ing => in

    # 下面 hu <=> f 這組寫法複雜一些，分情況討論
    #- derive/^hu$/fu/                  # hu => fu
    #- derive/^hong$/feng/              # hong => feng
    #- derive/^hu([in])$/fe$1/          # hui => fei, hun => fen
    #- derive/^hu([ao])/f$1/            # hua => fa, ...

    #- derive/^fu$/hu/                  # fu => hu
    #- derive/^feng$/hong/              # feng => hong
    #- derive/^fe([in])$/hu$1/          # fei => hui, fen => hun
    #- derive/^f([ao])/hu$1/            # fa => hua, ...

    # 模糊音定義先於簡拼定義，方可令簡拼支持以上模糊音
    - abbrev/^([a-z]).+$/$1/ # 簡拼（首字母）
    - abbrev/^([zcs]h).+$/$1/ # 簡拼（zh, ch, sh）

    # 自動糾正一些常見的按鍵錯誤
    - derive/([aeiou])ng$/$1gn/ # dagn => dang
    - derive/([dtngkhrzcs])o(u|ng)$/$1o/ # zho => zhong|zhou
    # - derive/ong$/on/ # zhonguo => zhong guo
    - derive/ao$/oa/ # hoa => hao
    - derive/([iu])a(o|ng?)$/a$1$2/ # tain => tian
